package trueblue.elearning.common.model;

import java.math.BigDecimal;

public interface SmUserModel {
	public String getUserid();
	public String getUsername();
	public String getMiddleName();
	public String getGivenName();
	public String getFamilyName();
	public String getUsernameEng();
	public String getLoginYn();
	public BigDecimal getLoginCnt();
	public String getLoginTime();
	public String getLangCd();
	public String getLangName();
	public String getUseYn();
	public String getStartDate();
	public String getEndDate();
	public String getStartDate1();
	public String getEndDate1();
	public String getDeptText();
	public String getWorkText();
	public String getMemberId();
	public String getMemberName();
	public String getCntCd();
	public String getCntName();
	public String getPmsMngYn();
	public String getPmsEisYn();
	public String getMobile();
	public String getEMail();
	public String getSmsEis();
	public String getSmsBlacklist();
	public String getSmsScheduler();
	public String getSmsMntrLv2();
	public String getSmsMntrLv3();
	public String getSmsMntrLv4();
	public String getMacAddrPcC();
	public String getMacAddrPcH();
	public String getMacAddrLaptop();
	public String getMacAddrPhone();
	public String getMacAddrTablet();
	public String getIpAddr();
	public String getViewJuminNo();
	public String getViewPersonal();
	public String getViewAccNo();
	public String getViewCardNo();
	public String getEditYn();
	public String getViewYn();
	public BigDecimal getLoginFailCnt();
	public String getLoginMsg();
	public String getRemark();
	public String getWorkDate();
	public String getWorkUser();
	public String getPasswd();
	public String getDePasswd();
	public String getFilePath();
	public String getComId();
	public String getSkin();
	
	public String getOrgChart01();
	public String getOrgChart02();
	public String getOrgChart03();
	public String getOrgChart04();
	public String getOrgChart05();
	public String getOrgChart06();
	public String getOrgChart07();
	public String getOrgChart08();
	public String getOrgChart09();
	public String getOrgChart10();
}
