server:
  port: 8088
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql